name: decker-engine
version: 0.1.0.0
github: "monofon/decker-engine"
license: BSD3
author: "Henrik Tramberend"
maintainer: "henrik@tramberend.de"
copyright: "Copyright 2020 Henrik Tramberend"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            tools

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/monofon/decker-engine#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - blaze-html
  - bytestring
  - conduit
  - containers
  - directory
  - either
  - fast-logger
  - filepath
  - hdaemonize
  - http-api-data
  - http-media
  - http-types
  - monad-logger
  - mtl
  - persistent
  - persistent-sqlite
  - persistent-template
  - relude
  - servant
  - servant-docs
  - servant-js
  - servant-server
  - text
  - time
  - transformers
  - wai
  - wai-extra
  - wai-cors
  - warp
  - pureMD5
  - random

library:
  source-dirs: src

executables:
  #decker-daemon:
    #main: Daemon
    #source-dirs: app
    #ghc-options:
      #- -threaded
      #- -rtsopts
      #- -with-rtsopts=-N
    #dependencies:
      #- base
      #- decker-engine
  decker-engine:
    main: Main
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - decker-engine

tests:
  decker-engine-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - decker-engine
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
